name: skip_n_call
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_stripe: ^9.4.0
  intl: ^0.17.0
  motion_toast: ^2.7.8
  firebase_core: ^2.18.0
  firebase_messaging: ^14.7.0
  flutter_local_notifications: ^16.1.0
  app_settings: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1


  flutter_lints: ^2.0.0
  flutter_svg: ^2.0.7
  jovial_svg: ^1.1.17
  shared_preferences: ^2.2.1
  http: ^1.1.0
  lottie: ^2.6.0
  shimmer: ^3.0.0
  loading_animation_widget: ^1.2.0+4
  swipe_refresh: ^1.0.2
  image_picker: ^1.0.4
  permission_handler: ^11.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/


flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

